application: xfox
version: 1
runtime: python
api_version: 1
derived_file_type:
- python_precompiled

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration : "1d"

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /a/.*
  script: account/views.py

- url: /u/.*
  script: account/views.py

- url: /d/.*
  script: dash/views.py
  
- url: /p/.*
  script: discussion/views.py
  
- url: /c/.*
  script: discussion/views.py
  
- url: /b/.*
  script: discussion/views.py
  
- url: /g/.*
  script: gs/views.py

- url: /test.*
  script: gaeunit.py
  
- url: /[a-z0-9-]{2,}.*
  script: discussion/views.py

- url: .*
  script: main.py
  
