application: xfox
version: 1
runtime: python
api_version: 1
derived_file_type:
- python_precompiled

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration : "10d"

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml
  
- url: /PIE.htc
  static_files:  static/PIE.htc
  upload:  static/PIE.htc
  mime_type:  text/x-component  
  expiration: "300d"
  
- url: /static
  static_dir: static
  expiration: "30d"

- url: /a/.*
  script: account/views.py

- url: /u/.*
  script: account/views.py

- url: /d/.*
  script: dash/views.py
  login: admin
  
- url: /p/.*
  script: discussion/views.py
  
- url: /c/.*
  script: discussion/views.py
  
- url: /b/.*
  script: discussion/views.py
  
- url: /f/.*
  script: discussion/views.py
  
- url: /g/.*
  script: gs/views.py

- url: /t/u/.*
  script: task/user.py
  login: admin

- url: /t/d/.*
  script: task/dis.py
  login: admin

- url: /s/s/.*
  script: task/system.py
  login: admin
  
- url: /test.*
  script: gaeunit.py
  
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /[a-z0-9-]{2,}.*
  script: discussion/views.py
  
- url: /_ah/login_required
  script: account/do_openid_login.py

- url: .*
  script: main.py
  
