application: vanilla2
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /a/.*
  script: account/views.py
  
- url: /b/.*
  script: discussion/views.py
  
- url: /test.*
  script: gaeunit.py
  
- url: .*
  script: main.py
